In [40]:
import numpy as np

In [41]:
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))

In [42]:
x = np.array([0.5, 0.1, -0.2])    # input
target = 0.6                      # errror = target - output
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

In [43]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_input

array([ 0.24, -0.46])

In [44]:
hidden_layer_output = sigmoid(hidden_layer_input)
hidden_layer_output

array([0.55971365, 0.38698582])

In [45]:
output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output_layer_in

-0.06012438223148006

In [46]:
output = sigmoid(output_layer_in)
output

0.48497343084992534

### Output error

In [47]:
## Backwards pass
## TODO: Calculate output error // the network's output error
error = target - output
error

0.11502656915007464

### Output layer's ERROR TERM

In [48]:
# TODO: Calculate error term for output layer // output layer's error term.
output_error_term = (target - output) * output * (1 - output)
output_error_term =             error * output * (1 - output)
output_error_term

0.028730669543515018

### Hidden layer's ERROR TERM

In [49]:
# TODO: Calculate error term for hidden layer // Use **backpropagation**
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * hidden_layer_output * (1 - hidden_layer_output)
hidden_error_term

array([ 0.00070802, -0.00204471])

### Delta weight

##### Delta weight: hidden layer -> output layer

In [50]:
# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# 1x1 * 1x1 * 1*2 = 1x2

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)

Change in weights for hidden layer to output layer:
[0.00804047 0.00555918]


##### Delta weight: input layer -> hidden layer

In [51]:
# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None] # [:, None] to create an axis of length one

In [52]:
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

Change in weights for input layer to hidden layer:
[[ 1.77005547e-04 -5.11178506e-04]
 [ 3.54011093e-05 -1.02235701e-04]
 [-7.08022187e-05  2.04471402e-04]]
