In [97]:
import numpy as np

In [98]:
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))

In [99]:
x = np.array([0.5, 0.1, -0.2])    # input
target = 0.6                      # errror = target - output
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

In [100]:
n_records = 360 # number of samples

In [101]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_input

array([ 0.24, -0.46])

In [102]:
hidden_layer_output = sigmoid(hidden_layer_input)
hidden_layer_output

array([0.55971365, 0.38698582])

In [103]:
output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output_layer_in

-0.06012438223148006

In [104]:
output = sigmoid(output_layer_in)
output

0.48497343084992534

### Output Error

In [105]:
## Backwards pass
## TODO: Calculate output error // the network's output error
error = target - output
error

0.11502656915007464

### Output Layer's ERROR TERM

In [106]:
# TODO: Calculate error term for output layer // output layer's error term.
output_error_term = (target - output) * output * (1 - output)
output_error_term =             error * output * (1 - output)
output_error_term

0.028730669543515018

### Hidden Error

In [107]:
hidden_error = np.dot(output_error_term, weights_hidden_output)

### Hidden Layer's ERROR TERM

In [108]:
# TODO: Calculate error term for hidden layer // Use **backpropagation**
# hidden_error_term = np.dot(output_error_term, weights_hidden_output) * hidden_layer_output * (1 - hidden_layer_output)
hidden_error * hidden_layer_output * (1 - hidden_layer_output)
hidden_error_term

array([ 0.00070802, -0.00204471])

### Update Change in weights

In [109]:
del_w_input_hidden = np.zeros(weights_input_hidden.shape)

del_w_input_hidden = hidden_error_term * x[:, None]
del_w_input_hidden

array([[ 3.54011093e-04, -1.02235701e-03],
       [ 7.08022187e-05, -2.04471402e-04],
       [-1.41604437e-04,  4.08942805e-04]])

In [110]:
del_w_hidden_output = np.zeros(weights_hidden_output.shape)

del_w_hidden_output = output_error_term * hidden_layer_output
del_w_hidden_output

array([0.01608095, 0.01111836])

### Update the change in weights

###### Weights input hidden

In [111]:
# (don't forget to division by n_records or number of samples)

In [112]:
delta_w_i_h = learnrate * del_w_input_hidden
delta_w_i_h

array([[ 1.77005547e-04, -5.11178506e-04],
       [ 3.54011093e-05, -1.02235701e-04],
       [-7.08022187e-05,  2.04471402e-04]])

In [113]:
weights_input_hidden += delta_w_i_h / n_records
weights_input_hidden

array([[ 0.50000049, -0.60000142],
       [ 0.1000001 , -0.20000028],
       [ 0.0999998 ,  0.70000057]])

In [114]:
delta_w_h_o = learnrate * del_w_hidden_output 
delta_w_h_o

array([0.00804047, 0.00555918])

In [115]:
weights_hidden_output += delta_w_h_o / n_records
weights_hidden_output

array([ 0.10002233, -0.29998456])

In [116]:
##### Alternatively,

##### Delta weight: input layer -> hidden layer

In [117]:
# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None] # [:, None] to create an axis of length one
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

Change in weights for input layer to hidden layer:
[[ 1.77005547e-04 -5.11178506e-04]
 [ 3.54011093e-05 -1.02235701e-04]
 [-7.08022187e-05  2.04471402e-04]]


##### Delta weight: hidden layer -> output layer

In [118]:
# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# 1x1 * 1x1 * 1*2 = 1x2

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)

Change in weights for hidden layer to output layer:
[0.00804047 0.00555918]
